- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    version: HEAD
    update: yes

- name: Symlink dotfiles using Stow
  shell: |
    stow {{ item }}
  args:
    chdir: "{{ dotfiles_dir }}"
    loop:
      - nvim
      - tmux
      - bash
      - git
    tags: stow
